# Generated by Django 2.2 on 2020-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=True, max_length=155)),
            ],
        ),
    ]
