# Generated by Django 2.2 on 2020-03-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Converter',
        ),
    ]
